// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "x_?Tx%2_s][,%AWaA[*4":
            case "roseright":return img`
...................ccbbbbcc............
...............bdddddddddddddb.........
............cddddddddddddddddddc.......
...........ecbddddddddddddddddddb......
...c.ee.e.eeefdddddddddddddddddddd.....
..bd.eeefeeeefddddddddddddddddddddb....
.bdd3eefeeeecddddddddddddddddddddddc...
cddddd.cceebdddddddddddddddddddddddd...
ddddc..dddddddddddddddddddddddddddddc..
ddb...ddddddddddddddddddddddddddddddd..
db....dddddddddddddddddddddddddddddddc.
b....cdddddddddcccdddddddddcdddddddddc.
c....dddddddddcccbddddddddc1cddddddddb.
.....dddddddbb1b1dbdddddddc11cdddddddd.
.....ddddddcdddd11cddddddc1ddddcdddddd.
.....dddddb1cd1dc1bbddddcdc11bd1bddddb.
.....bdddcd1b111bddcdddcdc1111cbddddd..
.....cdddc11b111bd1bdbc11b1111ccdddddc.
.....cdddf11bbdbb11dcd1111cbdcdbcbddbb.
.....dddddd11ddd111111111111d1bccdddbcc
....c.cdddcd11111bceeeeec11111fdcdddc.c
.......ddddc11111deeeeeeb111111cdddb..c
.......cddddc11111beeeec111111dbdddc.c.
........ddddcd111111ddd1111111cdddb....
.........ddddb111111111111111cddddc....
..........dddcfcdd111111ddbfbcbddc.....
..........dcfcfcbcccccfffcd1ccfdb......
..........dcbcd1ddbfeeefcc1d11ddc......
..........ccccd1ddd11dd111dc11cdcd.....
.........c111dd1bddbbcffeeef1dcc11c....
.........b111111ceeeeeeeeeeeb11111bb...
........bbb1111c.eeeeeeeeeee.c111cd1d..
.......d11dc11...eeeeeeeeeee...1db111b.
.......ddb.......eeeeeeeeeeee.....cddb.
.................eeeeeeeeeeee..........
.................eeeeeeeeeeee..........
...............c.eeeeeeeeeeee..........
................ceeeeeeeeeeeee.........
................eeeeeeeeeeeeee.........
................eeeeeeeeeeeeee.........
................eeeeeeeeeeeee..........
................eeeeeeeeeefc7c.........
.................cccc.....7777.........
................c777c.....7777.........
................c777......c777.........
................c77c.......777c........
................c77c.......cccc........
................ccbc........eee........
................eee....................
.................c.....................
`;
            case "J|NadRa1y,mG,T_UgN,|":
            case "roseleft":return img`
........................
........................
........................
........................
.........fffff..........
........f11111ff........
.......fb111111bf.......
.......f1111111dbf......
......fd111111dddf......
......fd11111ddddf......
......fd11dddddddf......
......f111dddddddf......
......f11fcddddddf......
.....fb1111bdddbf.......
.....f1b1bdfcfff........
.....fbfbffffffff.......
......fffffffffff.ff....
...........ffffffff.....
........f1b1bffffff.....
........fbfbffffff......
........................
........................
........................
........................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
