// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "J|NadRa1y,mG,T_UgN,|":
            case "roseleft":return img`
............bbbbbbc....................
........cdddddddddddddb................
......cddddddddddddddddddc.............
.....bddddddddddddddddddbfe............
....bdddddddddddddddddddfeee.e.ee.c....
...cddddddddddddddddddddfeeeeeeee.dc...
....dddddddddddddddddddddeeeee.eedddc..
..bdddddddddddddddddddddddcb....dddddc.
.cddddddddddddddddddddddddddddd..cdddd.
.ddddddddddddddddddddddddddddddd...bdd.
.ddddddddddddddddddddddddddddddd....bdc
cdddddddddcdddddddddfccdddddddddc....bc
cddddddddf1cddddddddcccfddddddddd....cc
ddddddddf11bdddddddb11c1bdddddddd.....c
ddddddcd1dd1cddddddc11ddddcdddddd......
cddddd1db11cdcddddbb1cd1dc1bddddd......
.dddddcc1111c1cdddc1bc111d11cdddb......
.dddddfc1111c11cbdb1dc111d11fdddc......
bcddbfb1cddc1111df111bddbb11fdddc......
ccdddfcc111111111111111d111dddddd......
.cdddc1f11111ceeeefcb111111fdddc.c.....
..cdddf111111deeeeee111111fdddd........
c.cddddb111111beeeeb11111bddddc........
...bdddb11111111dd111111dcdddd.........
....ddddf111111111111111ddddd..........
.....dddfbfdd1111111ddbfcddd...........
.....bdffc1dcffffffccdcfcfbd...........
.....cd1111dcffeeefbb11dcd.d...........
....dbdf11c111111111d11dfc.............
...c11bfd1feeecffcdddd1d1111c..........
..bb11111beeeeeeeeeeec111111b..........
.d11c111c.eeeeeeeeeee..1111bbb.........
c111dd1...eeeeeeeeeee...11.d11d........
c1db.....eeeeeeeeeeee.......ddd........
.........eeeeeeeeeeee..................
.........eeeeeeeeeeeec.................
.........eeeeeeeeeeeec.................
.........eeeeeeeeeeeec.................
........eeeeeeeeeeeeee.................
........eeeeeeeeeeeeee.................
.........eeeeeeeeeeeee.................
........c7ccceeeeeeeee.................
........7777.....ccc7..................
........7777......777c.................
........7777......777c.................
........777.......c77c.................
.......cc.........c77c.................
.......eee........cdb..................
...................eee.................
.......................................
`;
            case "x_?Tx%2_s][,%AWaA[*4":
            case "roseright":return img`
...................ccbbbbcc............
...............bdddddddddddddb.........
............cddddddddddddddddddc.......
...........ecbddddddddddddddddddb......
...c.ee.e.eeefdddddddddddddddddddd.....
..bd.eeefeeeefddddddddddddddddddddb....
.bdd3eefeeeecddddddddddddddddddddddc...
cddddd.cceebdddddddddddddddddddddddd...
ddddc..dddddddddddddddddddddddddddddc..
ddb...ddddddddddddddddddddddddddddddd..
db....dddddddddddddddddddddddddddddddc.
b....cdddddddddcccdddddddddcdddddddddc.
c....dddddddddcccbddddddddc1cddddddddb.
.....dddddddbb1b1dbdddddddc11cdddddddd.
.....ddddddcdddd11cddddddc1ddddcdddddd.
.....dddddb1cd1dc1bbddddcdc11bd1bddddb.
.....bdddcd1b111bddcdddcdc1111cbddddd..
.....cdddc11b111bd1bdbc11b1111ccdddddc.
.....cdddf11bbdbb11dcd1111cbdcdbcbddbb.
.....dddddd11ddd111111111111d1bccdddbcc
....c.cdddcd11111bceeeeec11111fdcdddc.c
.......ddddc11111deeeeeeb111111cdddb..c
.......cddddc11111beeeec111111dbdddc.c.
........ddddcd111111ddd1111111cdddb....
.........ddddb111111111111111cddddc....
..........dddcfcdd111111ddbfbcbddc.....
..........dcfcfcbcccccfffcd1ccfdb......
..........dcbcd1ddbfeeefcc1d11ddc......
..........ccccd1ddd11dd111dc11cdcd.....
.........c111dd1bddbbcffeeef1dcc11c....
.........b111111ceeeeeeeeeeeb11111bb...
........bbb1111c.eeeeeeeeeee.c111cd1d..
.......d11dc11...eeeeeeeeeee...1db111b.
.......ddb.......eeeeeeeeeeee.....cddb.
.................eeeeeeeeeeee..........
.................eeeeeeeeeeee..........
...............c.eeeeeeeeeeee..........
................ceeeeeeeeeeeee.........
................eeeeeeeeeeeeee.........
................eeeeeeeeeeeeee.........
................eeeeeeeeeeeee..........
................eeeeeeeeeefc7c.........
.................cccc.....7777.........
................c777c.....7777.........
................c777......c777.........
................c77c.......777c........
................c77c.......cccc........
................ccbc........eee........
................eee....................
.................c.....................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
