namespace SpriteKind {
    export const ghost = SpriteKind.create()
}
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    roseleft.setImage(img`
        ...........ccbbbbcc....................
        ........bdddddddddddddb................
        ......cddddddddddddddddddc.............
        .....bddddddddddddddddddbfe............
        ....ddddddddddddddddddddfeee.e.ee.c....
        ...bddddddddddddddddddddfeeeefeee.db...
        ..cddddddddddddddddddddddceeeefeebddb..
        ..ddddddddddddddddddddddddbeeccfdddddc.
        .cdddddddddddddddddddddddddddddc.cdddd.
        .ddddddddddddddddddddddddddddddd...bddc
        cddddddddddddddddddddddddddddddd....bdc
        cdddddddddcdddddddddcccdddddddddc....bb
        bddddddddc1cddddddddccccddddddddd....cc
        ddddddddc11bdddddddbd1b1bbddddddd......
        ddddddcdddddcddddddc11ddddcdddddd......
        bddddb1db11cdcddddbb1cd1dc1bddddd......
        fdddddbc1111cdcdddcddb111d11fdddb......
        cdddddfc1111b11cbdc1db111b11cdddc......
        bbdddcbdcdbc1111dcd11bbdbc11fdddb......
        ccdddfcb1d111111111111ddd11dddddd......
        .cdddcdf11111ceeeeecb111111fdddb.c.....
        ..cdddc111111beeeeeed11111cdddd........
        c.cdddbb111111ceeeeb11111bddddc........
        ...bdddc1111111ddd111111dcdddd.........
        ....ddddc111111111111111bdddd..........
        ....cddbcbfbdd111111ddcfcddd...........
        .....bdfcc1dcfffcccccbcfcfcd...........
        .....cdd11ddccfeeefcdd1dcbfd...........
        ....bcdf11cd111dd11ddd1dfccc...........
        ...c11ccd1feeeffcbbddb1dd111c..........
        ..bb11111beeeeeeeeeeec111111d..........
        .b1dc111c.eeeeeeeeeee.c1111bbd.........
        b111bd1...eeeeeeeeeee...11cd11d........
        cddc.....eeeeeeeeeeee.......bdd........
        .........eeeeeeeeeeee..................
        .........eeeeeeeeeeee..................
        .........eeeeeeeeeeeec.................
        ........eeeeeeeeeeeeee.................
        ........eeeeeeeeeeeeee.................
        ........eeeeeeeeeeeeee.................
        .........eeeeeeeeeeeee.................
        ........c7cfceeeeeeeee.................
        ........7777......ccc..................
        ........7777.....c777c.................
        ........777c......777c.................
        ........777.......c77c.................
        .......cccc.......c777.................
        .......eee........cbcc.................
        ...................eee.................
        .......................................
        `)
    LINE.setImage(img`
        ........................
        ........................
        ........................
        ........................
        ..........fffff.........
        ........ff1111bff.......
        .......fb1111111bf......
        .......f111111111f......
        ......fd1111111ffff.....
        ......fd111dd1c111bf....
        ......fb11fcdf1b1bff....
        ......f11111bfbfbff.....
        ......f1b1bdfcffff......
        ......fbfbfcfcccf.......
        ......ffffffffff........
        .........ffffff.........
        .........ffffff.........
        .........fffffff..f.....
        ..........fffffffff.....
        ...........fffffff......
        ........................
        ........................
        ........................
        ........................
        `)
    pause(500)
    LINE.setImage(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fdd111111ddf......
        ......fbdd1111dddf......
        ......fcdbfddfbdbf......
        .......fbcf11fcbfff.....
        .......ffb1111bcfbcf....
        ........fcdb1bdfbbbf....
        .......ffffffffffcf.....
        .....fcb1bcfffff........
        .....f1b1b1ffff.........
        ......ffbff.............
        ........................
        ........................
        ........................
        ........................
        ........................
        `)
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    roseleft.setImage(assets.image`roseright`)
    // once you match it'll revert back to the original sprite
    LINE.setImage(img`
        ........................
        ........................
        ........................
        ........................
        .........fffff..........
        .......ffb1111ff........
        ......fb1111111bf.......
        ......f111111111f.......
        .....ffff1111111df......
        ....fb111c1dd111df......
        ....ffb1b1fdcf11bf......
        .....ffbfbfb11111f......
        ......ffffcfdb1b1f......
        .......fcccfcfbfbf......
        ........ffffffffff......
        .........ffffff.........
        .........ffffff.........
        .....f..fffffff.........
        .....fffffffff..........
        ......fffffff...........
        ........................
        ........................
        ........................
        ........................
        `)
    pause(500)
    LINE.setImage(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fdd111111ddf......
        ......fbdd1111dddf......
        ......fcdbfddfbdbf......
        .......fbcf11fcbfff.....
        .......ffb1111bcfbcf....
        ........fcdb1bdfbbbf....
        .......ffffffffffcf.....
        .....fcb1bcfffff........
        .....f1b1b1ffff.........
        ......ffbff.............
        ........................
        ........................
        ........................
        ........................
        ........................
        `)
})
function updSCORE (note: Sprite) {
    if (Math.abs(note.y - LINE.y) <= 9) {
        info.changeScoreBy(5)
        epl.setImage(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . 3 3 3 3 3 3 . . . . . 
            . . . . . 3 . . . . . . . . . . 
            . . . . . 3 . . . . . . . . . . 
            . . . . . 3 . 3 . . . . . . . . 
            . . . . . 3 3 3 . . . . . . . . 
            . . . . . 3 . . . . . . . . . . 
            . . . . . 3 . . . . . . . . . . 
            . . . . . 3 3 3 3 3 . . . . . . 
            . . . . . 3 . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `)
    } else if (Math.abs(note.y - LINE.y) >= 17) {
        info.changeScoreBy(5)
        epl.setImage(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . 3 3 . . . . . . . . . 
            . . . . . 3 . . . . . . . . . . 
            . . . . . 3 . . . . . . . . . . 
            . . . . . 3 . . . . . . . . . . 
            . . . . . 3 . . . . . . . . . . 
            . . . . . 3 . . . . . . . . . . 
            . . . . . 3 . . . . . . . . . . 
            . . . . . 3 . . . . . . . . . . 
            . . . . . 3 . . . . 3 3 3 3 . . 
            . . . . . 3 3 3 3 3 . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `)
    } else {
        info.changeScoreBy(10)
        epl.setImage(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . 3 3 3 3 . . . . . . . 
            . . . . . 3 3 . . 3 3 . . . . . 
            . . . . . 3 3 . . . 3 3 . . . . 
            . . . . . 3 3 . . . . 3 . . . . 
            . . . . . 3 3 . . . . 3 . . . . 
            . . . . . 3 3 . . . 3 . . . . . 
            . . . . . 3 3 3 3 3 . . . . . . 
            . . . . . 3 3 . . . . . . . . . 
            . . . . . 3 . . . . . . . . . . 
            . . . . . 3 . . . . . . . . . . 
            . . . . . 3 . . . . . . . . . . 
            . . . . . 3 . . . . . . . . . . 
            . . . . . 3 . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `)
    }
}
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.ghost, function (sprite, otherSprite) {
    if (controller.left.isPressed() || controller.right.isPressed()) {
        updSCORE(sprite)
        sprites.destroy(sprite, effects.spray, 500)
    }
})
let projectile: Sprite = null
let epl: Sprite = null
let LINE: Sprite = null
let roseleft: Sprite = null
roseleft = sprites.create(img`
    ...........ccbbbbcc....................
    ........bdddddddddddddb................
    ......cddddddddddddddddddc.............
    .....bddddddddddddddddddbfe............
    ....ddddddddddddddddddddfeee.e.ee.c....
    ...bddddddddddddddddddddfeeeefeee.db...
    ..cddddddddddddddddddddddceeeefeebddb..
    ..ddddddddddddddddddddddddbeeccfdddddc.
    .cdddddddddddddddddddddddddddddc.cdddd.
    .ddddddddddddddddddddddddddddddd...bddc
    cddddddddddddddddddddddddddddddd....bdc
    cdddddddddcdddddddddcccdddddddddc....bb
    bddddddddc1cddddddddccccddddddddd....cc
    ddddddddc11bdddddddbd1b1bbddddddd......
    ddddddcdddddcddddddc11ddddcdddddd......
    bddddb1db11cdcddddbb1cd1dc1bddddd......
    fdddddbc1111cdcdddcddb111d11fdddb......
    cdddddfc1111b11cbdc1db111b11cdddc......
    bbdddcbdcdbc1111dcd11bbdbc11fdddb......
    ccdddfcb1d111111111111ddd11dddddd......
    .cdddcdf11111ceeeeecb111111fdddb.c.....
    ..cdddc111111beeeeeed11111cdddd........
    c.cdddbb111111ceeeeb11111bddddc........
    ...bdddc1111111ddd111111dcdddd.........
    ....ddddc111111111111111bdddd..........
    ....cddbcbfbdd111111ddcfcddd...........
    .....bdfcc1dcfffcccccbcfcfcd...........
    .....cdd11ddccfeeefcdd1dcbfd...........
    ....bcdf11cd111dd11ddd1dfccc...........
    ...c11ccd1feeeffcbbddb1dd111c..........
    ..bb11111beeeeeeeeeeec111111d..........
    .b1dc111c.eeeeeeeeeee.c1111bbd.........
    b111bd1...eeeeeeeeeee...11cd11d........
    cddc.....eeeeeeeeeeee.......bdd........
    .........eeeeeeeeeeee..................
    .........eeeeeeeeeeee..................
    .........eeeeeeeeeeeec.................
    ........eeeeeeeeeeeeee.................
    ........eeeeeeeeeeeeee.................
    ........eeeeeeeeeeeeee.................
    .........eeeeeeeeeeeee.................
    ........c7cfceeeeeeeee.................
    ........7777......ccc..................
    ........7777.....c777c.................
    ........777c......777c.................
    ........777.......c77c.................
    .......cccc.......c777.................
    .......eee........cbcc.................
    ...................eee.................
    .......................................
    `, SpriteKind.Player)
LINE = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fdd111111ddf......
    ......fbdd1111dddf......
    ......fcdbfddfbdbf......
    .......fbcf11fcbfff.....
    .......ffb1111bcfbcf....
    ........fcdb1bdfbbbf....
    .......ffffffffffcf.....
    .....fcb1bcfffff........
    .....f1b1b1ffff.........
    ......ffbff.............
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.ghost)
epl = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . 3 . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Player)
let list2 = [sprites.castle.skellyAttackLeft1, sprites.castle.skellyAttackRight2]
LINE.setPosition(50, 100)
roseleft.setPosition(135, 70)
epl.setPosition(136, 20)
music.play(music.createSong(assets.song`mySong`), music.PlaybackMode.LoopingInBackground)
info.setScore(0)
game.onUpdateInterval(music.beat(BeatFraction.Double), function () {
    projectile = sprites.createProjectileFromSide(list2[randint(0, 1)], 0, 50)
    projectile.setPosition(50, 0)
})
