@namespace
class SpriteKind:
    ghost = SpriteKind.create()

def on_left_pressed():
    roseleft.set_image(img("""
        ...........ccbbbbcc....................
                ........bdddddddddddddb................
                ......cddddddddddddddddddc.............
                .....bddddddddddddddddddbfe............
                ....ddddddddddddddddddddfeee.e.ee.c....
                ...bddddddddddddddddddddfeeeefeee.db...
                ..cddddddddddddddddddddddceeeefeebddb..
                ..ddddddddddddddddddddddddbeeccfdddddc.
                .cdddddddddddddddddddddddddddddc.cdddd.
                .ddddddddddddddddddddddddddddddd...bddc
                cddddddddddddddddddddddddddddddd....bdc
                cdddddddddcdddddddddcccdddddddddc....bb
                bddddddddc1cddddddddccccddddddddd....cc
                ddddddddc11bdddddddbd1b1bbddddddd......
                ddddddcdddddcddddddc11ddddcdddddd......
                bddddb1db11cdcddddbb1cd1dc1bddddd......
                fdddddbc1111cdcdddcddb111d11fdddb......
                cdddddfc1111b11cbdc1db111b11cdddc......
                bbdddcbdcdbc1111dcd11bbdbc11fdddb......
                ccdddfcb1d111111111111ddd11dddddd......
                .cdddcdf11111ceeeeecb111111fdddb.c.....
                ..cdddc111111beeeeeed11111cdddd........
                c.cdddbb111111ceeeeb11111bddddc........
                ...bdddc1111111ddd111111dcdddd.........
                ....ddddc111111111111111bdddd..........
                ....cddbcbfbdd111111ddcfcddd...........
                .....bdfcc1dcfffcccccbcfcfcd...........
                .....cdd11ddccfeeefcdd1dcbfd...........
                ....bcdf11cd111dd11ddd1dfccc...........
                ...c11ccd1feeeffcbbddb1dd111c..........
                ..bb11111beeeeeeeeeeec111111d..........
                .b1dc111c.eeeeeeeeeee.c1111bbd.........
                b111bd1...eeeeeeeeeee...11cd11d........
                cddc.....eeeeeeeeeeee.......bdd........
                .........eeeeeeeeeeee..................
                .........eeeeeeeeeeee..................
                .........eeeeeeeeeeeec.................
                ........eeeeeeeeeeeeee.................
                ........eeeeeeeeeeeeee.................
                ........eeeeeeeeeeeeee.................
                .........eeeeeeeeeeeee.................
                ........c7cfceeeeeeeee.................
                ........7777......ccc..................
                ........7777.....c777c.................
                ........777c......777c.................
                ........777.......c77c.................
                .......cccc.......c777.................
                .......eee........cbcc.................
                ...................eee.................
                .......................................
    """))
    LINE.set_image(img("""
        ........................
                ........................
                ........................
                ........................
                ..........fffff.........
                ........ff1111bff.......
                .......fb1111111bf......
                .......f111111111f......
                ......fd1111111ffff.....
                ......fd111dd1c111bf....
                ......fb11fcdf1b1bff....
                ......f11111bfbfbff.....
                ......f1b1bdfcffff......
                ......fbfbfcfcccf.......
                ......ffffffffff........
                .........ffffff.........
                .........ffffff.........
                .........fffffff..f.....
                ..........fffffffff.....
                ...........fffffff......
                ........................
                ........................
                ........................
                ........................
    """))
    pause(500)
    LINE.set_image(img("""
        ........................
                ........................
                ........................
                ........................
                ..........ffff..........
                ........ff1111ff........
                .......fb111111bf.......
                .......f11111111f.......
                ......fd11111111df......
                ......fdd111111ddf......
                ......fbdd1111dddf......
                ......fcdbfddfbdbf......
                .......fbcf11fcbfff.....
                .......ffb1111bcfbcf....
                ........fcdb1bdfbbbf....
                .......ffffffffffcf.....
                .....fcb1bcfffff........
                .....f1b1b1ffff.........
                ......ffbff.............
                ........................
                ........................
                ........................
                ........................
                ........................
    """))
controller.left.on_event(ControllerButtonEvent.PRESSED, on_left_pressed)

def on_right_pressed():
    roseleft.set_image(assets.image("""
        roseright
    """))
    # once you match it'll revert back to the original sprite
    LINE.set_image(img("""
        ........................
                ........................
                ........................
                ........................
                .........fffff..........
                .......ffb1111ff........
                ......fb1111111bf.......
                ......f111111111f.......
                .....ffff1111111df......
                ....fb111c1dd111df......
                ....ffb1b1fdcf11bf......
                .....ffbfbfb11111f......
                ......ffffcfdb1b1f......
                .......fcccfcfbfbf......
                ........ffffffffff......
                .........ffffff.........
                .........ffffff.........
                .....f..fffffff.........
                .....fffffffff..........
                ......fffffff...........
                ........................
                ........................
                ........................
                ........................
    """))
    pause(500)
    LINE.set_image(img("""
        ........................
                ........................
                ........................
                ........................
                ..........ffff..........
                ........ff1111ff........
                .......fb111111bf.......
                .......f11111111f.......
                ......fd11111111df......
                ......fdd111111ddf......
                ......fbdd1111dddf......
                ......fcdbfddfbdbf......
                .......fbcf11fcbfff.....
                .......ffb1111bcfbcf....
                ........fcdb1bdfbbbf....
                .......ffffffffffcf.....
                .....fcb1bcfffff........
                .....f1b1b1ffff.........
                ......ffbff.............
                ........................
                ........................
                ........................
                ........................
                ........................
    """))
controller.right.on_event(ControllerButtonEvent.PRESSED, on_right_pressed)

def updSCORE(note: Sprite):
    if abs(note.y - LINE.y) <= 9:
        info.change_score_by(5)
    elif abs(note.y - LINE.y) >= 17:
        info.change_score_by(5)
    else:
        info.change_score_by(10)

def on_on_overlap(sprite, otherSprite):
    if controller.left.is_pressed() or controller.right.is_pressed():
        updSCORE(sprite)
        sprites.destroy(sprite, effects.spray, 500)
sprites.on_overlap(SpriteKind.projectile, SpriteKind.ghost, on_on_overlap)

projectile: Sprite = None
LINE: Sprite = None
roseleft: Sprite = None
roseleft = sprites.create(img("""
        ...........ccbbbbcc....................
            ........bdddddddddddddb................
            ......cddddddddddddddddddc.............
            .....bddddddddddddddddddbfe............
            ....ddddddddddddddddddddfeee.e.ee.c....
            ...bddddddddddddddddddddfeeeefeee.db...
            ..cddddddddddddddddddddddceeeefeebddb..
            ..ddddddddddddddddddddddddbeeccfdddddc.
            .cdddddddddddddddddddddddddddddc.cdddd.
            .ddddddddddddddddddddddddddddddd...bddc
            cddddddddddddddddddddddddddddddd....bdc
            cdddddddddcdddddddddcccdddddddddc....bb
            bddddddddc1cddddddddccccddddddddd....cc
            ddddddddc11bdddddddbd1b1bbddddddd......
            ddddddcdddddcddddddc11ddddcdddddd......
            bddddb1db11cdcddddbb1cd1dc1bddddd......
            fdddddbc1111cdcdddcddb111d11fdddb......
            cdddddfc1111b11cbdc1db111b11cdddc......
            bbdddcbdcdbc1111dcd11bbdbc11fdddb......
            ccdddfcb1d111111111111ddd11dddddd......
            .cdddcdf11111ceeeeecb111111fdddb.c.....
            ..cdddc111111beeeeeed11111cdddd........
            c.cdddbb111111ceeeeb11111bddddc........
            ...bdddc1111111ddd111111dcdddd.........
            ....ddddc111111111111111bdddd..........
            ....cddbcbfbdd111111ddcfcddd...........
            .....bdfcc1dcfffcccccbcfcfcd...........
            .....cdd11ddccfeeefcdd1dcbfd...........
            ....bcdf11cd111dd11ddd1dfccc...........
            ...c11ccd1feeeffcbbddb1dd111c..........
            ..bb11111beeeeeeeeeeec111111d..........
            .b1dc111c.eeeeeeeeeee.c1111bbd.........
            b111bd1...eeeeeeeeeee...11cd11d........
            cddc.....eeeeeeeeeeee.......bdd........
            .........eeeeeeeeeeee..................
            .........eeeeeeeeeeee..................
            .........eeeeeeeeeeeec.................
            ........eeeeeeeeeeeeee.................
            ........eeeeeeeeeeeeee.................
            ........eeeeeeeeeeeeee.................
            .........eeeeeeeeeeeee.................
            ........c7cfceeeeeeeee.................
            ........7777......ccc..................
            ........7777.....c777c.................
            ........777c......777c.................
            ........777.......c77c.................
            .......cccc.......c777.................
            .......eee........cbcc.................
            ...................eee.................
            .......................................
    """),
    SpriteKind.player)
LINE = sprites.create(img("""
        ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......f11111111f.......
            ......fd11111111df......
            ......fdd111111ddf......
            ......fbdd1111dddf......
            ......fcdbfddfbdbf......
            .......fbcf11fcbfff.....
            .......ffb1111bcfbcf....
            ........fcdb1bdfbbbf....
            .......ffffffffffcf.....
            .....fcb1bcfffff........
            .....f1b1b1ffff.........
            ......ffbff.............
            ........................
            ........................
            ........................
            ........................
            ........................
    """),
    SpriteKind.ghost)
list2 = [sprites.castle.skelly_attack_left1,
    sprites.castle.skelly_attack_right2]
LINE.set_position(50, 100)
roseleft.set_position(135, 70)
music.play(music.create_song(assets.song("""
        mySong
    """)),
    music.PlaybackMode.LOOPING_IN_BACKGROUND)
info.set_score(0)

def on_update_interval():
    global projectile
    projectile = sprites.create_projectile_from_side(list2[randint(0, 1)], 0, 50)
    projectile.set_position(50, 0)
game.on_update_interval(music.beat(BeatFraction.DOUBLE), on_update_interval)

